### ISSUE TITLE
Doujin.favorites doesn't show right value

### ISSUE THREAD

**Issue by Wiichele** [moe-ka/nhentai.py#10]
Tested with 325693

```python
import nhentai 
d = nhentai.get_doujin(325693) 
d.favorites 
0
```

and others.

**Comment by moe-ka** [comment]
it apparently shows 0 for galleries uploaded in the last days,
this field probably updates periodically.

**Comment by hentai-chan** [comment]
> it apparently shows 0 for galleries uploaded in the last 10 days,

Do you have a source for that? Would be great if we could compile a list of references for the API

**Comment by hysrx** [comment]
> 
> 
> > it apparently shows 0 for galleries uploaded in the last 10 days,
> 
> Do you have a source for that? Would be great if we could compile a list of references for the API

May not be 10 days, but simply using `get_homepage()`, I can recreate the behaviour with the following:

```python
>>> import nhentai
>>> for doujin in nhentai.get_homepage():
...     print(doujin.favorites)
...
0
0
0
0
0
... (20 more 0 responses)
```

**Comment by moe-ka** [comment]
can you check the upload date on those?
could also be a good idea to add that as a field

**Comment by hysrx** [comment]
> 
> 
> can you check the upload date on those?
> could also be a good idea to add that as a field

Are those sent back from the API?

**Comment by moe-ka** [comment]
> Are those sent back from the API?
yes, upload_date under galleries

**Comment by hysrx** [comment]
> 
> 
> can you check the upload date on those?
> could also be a good idea to add that as a field

Added upload date to findings

**Comment by hentai-chan** [comment]
I just checked this with a script, so going over all home page doujins, the first one with `num_pages != 0` is

```python
name = "(C91) [UNKNOWN MEAT (Kojima Video)] Niku Elf Shirokuro [English] [BSN]"
num_favorites = 550
upload date= "2020-09-03 05:48:14"
```

So, this was `15 days, 11:48:30.235115` ago. Though, as @hysrx mentioned it takes a while after all doujins have correct values.
