### ISSUE TITLE
Tag IDs are opaque

### ISSUE THREAD

**Issue by moe-ka** [moe-ka/nhentai.py#6]
tag IDs are opaque and there's no way to search galleries with a tag using its name
and there are no api endpoints that could convert between id/name.

possible conversion methods:
### tag name to ID:
tags can be scraped from f"https://nhentai.net/{tag_type}/{tag_name}"
where tag_type is one of {tags, artist, character, parody, group}
and tag_name is the name with spaces replaced by dashes (-).

```python
>>> tag_pattern = re.compile(br'tag-(\d+)')
>>> tag_pattern.search(requests.get('https://nhentai.net/character/kotori-minami').content)[1]
b'18548'
```

### tag ID to name:
gallery tags contain the tag name and id, and so it's possible to use `search_tagged(tag_id)` 
and find the tag with the given id, not a perfect solution since not all tags are used by atleast one gallery.

```python
>>> id = 1234
>>> tags = nhentai.search_tagged(id)[0].tags
>>> next(filter(lambda tag: tag.id == id, tags), None).name
'yuki nagato'
```

**Comment by hentai-chan** [comment]
Looks like we are working on the same problem! (☞ﾟヮﾟ)☞ I know that `https://nhentai.net/tags/?page={i}` for `i` in `[1,25]` provides a page-by-page collection of all unique tags. I was thinking about writing a scraper that stores all tags and ids in a config file that gets created in `master` as  part of a build procedure.

**Comment by moe-ka** [comment]
> Looks like we are working on the same problem! (☞ﾟヮﾟ)☞ I know that `https://nhentai.net/tags/?page={i}` for `i` in `[1,25]` provides a page-by-page collection of all unique tags. I was thinking about writing a scraper that stores all tags and ids in a config file that gets created in `master` as part of a build procedure.

new/removed tags would be an issue, also you'd need to scrape all the other tag types too.

**Comment by hentai-chan** [comment]
Hm you are right, I haven't thought about the other tags when I wrote my last message. I think I have found an another solution that solves this problem partially, but I need to put my ideas to test first. I'll let you know if it is any good.

**Comment by hysrx** [comment]
Thought I'd chime in, while I don't have any thought on how to solve this, I thought I should just mention this in the off chance it could help - you can search using syntax like `character:"kotori minami"`

**Comment by hentai-chan** [comment]
I finally got around writing this, as @hysrx said one way to do it would be by using their built-in query, cf.

```python
# use "/api/galleries/search" as endpoint
@staticmethod
def search_by_query(tag_name: str, timeout: Tuple[float, float] = RequestHandler.TIMEOUT) -> dict:
    response = Hentai.call_api(urljoin(Hentai.HOME, '/api/galleries/search'), timeout, params = { 'query' : tag_name})
    return response['result']

# invoke 
print(search_by_query('tag:loli'))
```

this returns for instance a list of dictionaries that contain the doujin's meta data. Should be easy enough to write something that uses this project's methods.

**Comment by moe-ka** [comment]
I'll close this for now then

**Comment by hysrx** [comment]
> I finally got around writing this, as @hysrx said one way to do it would be by using their built-in query, cf.
> 
> ```python
> # use "/api/galleries/search" as endpoint
> @staticmethod
> def search_by_query(query: str, timeout: Tuple[float, float] = RequestHandler.TIMEOUT) -> List[dict]:
>     response = Hentai.call_api(urljoin(Hentai.HOME, '/api/galleries/search'), timeout, params = { 'query' : query})
>     return response['result']
> 
> # invoke 
> print(search_by_query('tag:loli'))
> ```
> 
> this returns for instance a list of dictionaries that contain the doujin's meta data. Should be easy enough to write something that uses this project's methods.
> 
> **+++Update+++**
> I just noticed that
> ```python
> nhentai.search(query:str, page:int, sort_by:str) -> List[Doujin]
> ```
> already implements such a search query. Great! but! this is not a perfect solution because the result always caps at 25 doujin within range of the search query as is indicated by the `per_page` field in this [response](https://nhentai.net/api/galleries/search?query=tag:loli). So, the hunt goes on. I am not even sure anymore if there's an solution using the API for similar problems since this would also affect queries by authors, categories, etc. - so they all max out prematurely. But something interesting seems to happen when you couple queries with pages:
> 
> ```
> https://nhentai.net/api/galleries/search?query=tag:loli?page-1
> https://nhentai.net/api/galleries/search?query=tag:loli?page-2
> https://nhentai.net/api/galleries/search?query=tag:loli?page-3
> https://nhentai.net/api/galleries/search?query=tag:loli?page-4
> https://nhentai.net/api/galleries/search?query=tag:loli?page-5
> ```
> 
> I am not sure if this immitates a pagination because the results are unexpected to what one think would happen, maybe someone else can see how these changes come come into effect.
> 
> **+++Update 2+++**
> Never mind, it's actually 
> ```
> https://nhentai.net/api/galleries/search?query=tag:loli&page=1
> https://nhentai.net/api/galleries/search?query=tag:loli&page=2
> https://nhentai.net/api/galleries/search?query=tag:loli&page=3
> ```
> and so on. Guess this solves ALL problems at once!

Will note that its safer to use `tag:"loli"` to try to mitigate any issues related to spaces ij tags
